### ISSUE TITLE
Request for Model Architectures Found through BO Hyperparameter Tuning Method

### ISSUE THREAD

**Issue by excelsior399** [AISyLab/AutoSCA#1]
Hello!

I am so interested in your hyperparameter tuning works. I'm currently trying to reproduce it and want to compare models you find with my own, but I notice that you did not share your best model architectures, especially CNN. Could you please provide the details of these model architectures? Having access to this information would greatly assist in accurately comparing the experimental results.

Thank you in advance for your help!

**Comment by wu-lichao** [comment]
Hi, 

Thanks for your interest in our paper. Unfortunately, we don't have the best model-saving as a standalone step. Everything is performed automatically in the code.
Maybe you could run a new hyperparameter search; it should run very fast.

Kind regards,
Lichao

**Comment by excelsior399** [comment]
ok I'll try it, thanks again!
